name: backup
on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  backup:
    name: production-firestore
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: cusec-2021-production
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: gcloud firestore export gs://cusec-2021-production-backup
