name: branches
on:
  push:
    branches:
      - "**"
      - "!master"
      - "!develop"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run export
      - name: Firestore unit tests against emulator
        run: |
          java -version
          npx firebase-tools emulators:exec --only firestore --project cusec-2021-staging 'npm run test'
