name: staging
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - name: Install Dependencies
        run: npm ci
      - name: Build & Export
        run: npm run export-staging
      - name: Firestore unit tests against emulator
        run: |
          java -version
          npx firebase-tools emulators:exec --only firestore --project cusec-2021-staging 'npm run test'
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: out
          path: out
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: out
          path: out
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy -P staging --only hosting,firestore,storage
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
