name: pull-request
on: pull_request

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - name: Install Dependencies
        run: npm ci
      - name: Build & Export
        run: npm run export-staging
      - uses: FirebaseExtended/action-hosting-deploy@v0.6-alpha
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CUSEC_2021_STAGING }}"
          projectId: staging
          expires: 14d
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
